### ISSUE TITLE
Feather M0 Idle Power Draw

### ISSUE THREAD

**Issue by thejimster82** [UVA-DSI/sensenet#5] opened 2019-11-17 22:39 UTC
The Feather M0 LoRa draws about 0.37mA of current when idling using the sleepydog library. It would be ideal if we could push this down much further to the 0.01 or even 0.001 mA range and we should begin to explore other methods for doing this or other boards entirely that will be able to go lower than the m0 can possibly go.

**Comment by unixjazz** [comment] 2020-01-13 02:36
The Feather M0 is not meant for low-power applications: because of the circuitry for the external battery, the LDO, and the peripherals we might not be able to bring it lower than 300uA in sleep mode.

**Comment by krad246** [comment] 2020-01-13 03:30
Which board do we have? Feather M0 LoRa right? Probably should spend some time looking at where the power draws are coming from in the first place. 

Where's the power measurement coming from? VBUS? If so, then that current may be going somewhere else.

This is the schematic of the Feather M0 LoRa, unless I'm mistaken

![adafruit_products_M0SCHEM](https://cdn-learn.adafruit.com/assets/assets/000/032/914/original/feather_schem.png?1465421956)

Inspecting the schematic, I see that the LDO is in the direct path. If you're measuring on the input side, then you're also measuring the ~90 uA quiescent current from it.

Looking at table 37-10 from [ATSAMD21G18 datasheet](http://ww1.microchip.com/downloads/en/DeviceDoc/SAMD21-Family-DataSheet-DS40001882D.pdf), the standby current is worst case ~15 uA.

Looking at the actual LoRa chip behavior suggests that it doesn't matter in the best case.

![image](https://user-images.githubusercontent.com/39471261/72231732-13f87e00-358b-11ea-9b99-3758599a6bac.png)

Could be the battery charging IC, perhaps?

![image](https://user-images.githubusercontent.com/39471261/72231969-52db0380-358c-11ea-86d4-877c2ee60d90.png)

I also noticed some other places where current could be consumed, like the resistor divider with R3 and R6. With a nominal VBAT = 3.3 V, we get 16.5 uA through the divider. I'm also a bit suspicious of the resistor on PROG for the IC.

Lastly, there are some LEDs on the board that might be sinking a little current.

Evidently there are still more savings possible... need to characterize it by checking the paths really. I think it can be explained though.

**Comment by unixjazz** [comment] 2020-01-13 03:53
As I mentioned above: the culprits may be the battery charging IC and the LDO. We can still try to squeeze a few uA out, though. The MCU itself is not the issue here, but the Feather M0 board.

**Comment by unixjazz** [comment] 2020-02-19 21:54
closing this as the Feather M0 ** works as designed. **

**Closed as completed by unixjazz** 2020-02-19 21:54 UTC
